---
- name: APT key | Add MongoDB key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
  register: mongodb_key

- name: APT repository | Add MongoDB repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
  register: mongodb_repository

- name: APT | Update cache
  apt: update_cache=yes
  when: mongodb_key|changed or mongodb_repository|changed

- name: APT | Install mongodb
  apt: pkg=mongodb-org state=present

- command: pip install {{ item }}
  with_items:
    - pymongo

- name: Move mongodb conf file
  template: src=mongod.conf dest=/etc/mongod.conf

- name: Service | Start mongodb
  service: name=mongod state=started
- mongodb_user: database={{ mongodb.database }} name={{ mongodb.user }} password={{ mongodb.password }} roles='readWrite,dbAdmin,userAdmin' state=present
- mongodb_user: database=foo name=mike password=mikepassword roles='readWrite,dbAdmin,userAdmin' state=present